### ISSUE TITLE
"cannot unmarshal object" error when running the program

### ISSUE THREAD

**Issue by Lordmau5** [lolPants/BeatSaverDownloader#1]
![image](https://user-images.githubusercontent.com/1345036/43726355-394c37ac-999f-11e8-8dcf-a82abe5db347.png)

Seems like on some songs (probably more than this one) it causes this error to happen.
I've tried to look through the code already, but as I'm not that familiar with Go, I didn't see where it could happen.

`2018/08/06 17:35:44 json: cannot unmarshal object into Go struct field BeatSaver.songs of type []main.Song`

**Comment by lolPants** [comment]
Fixed as of 766dc4d04069474bed57d194e91e641de858820c
